
GET http://localhost:5000/users


###

POST http://localhost:5000/users/add
Content-Type: application/json

{
    "email": "bobby@gmail.com",
    "password": "password",
    "firstName": "Bobby",
    "lastName": "Ray"
}
